//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynDNS_Updater.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Static {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Static() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynDNS_Updater.Language.Static", typeof(Static).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoWebRequest.
        /// </summary>
        internal static string ConsoleLog_DoWebRequest {
            get {
                return ResourceManager.GetString("ConsoleLog_DoWebRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        internal static string IPv4 {
            get {
                return ResourceManager.GetString("IPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        internal static string IPv6 {
            get {
                return ResourceManager.GetString("IPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abuse.
        /// </summary>
        internal static string ResponseAbuse {
            get {
                return ResourceManager.GetString("ResponseAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to badauth.
        /// </summary>
        internal static string ResponseBadAuth {
            get {
                return ResourceManager.GetString("ResponseBadAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnserr.
        /// </summary>
        internal static string ResponseError {
            get {
                return ResourceManager.GetString("ResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good.
        /// </summary>
        internal static string ResponseGood {
            get {
                return ResourceManager.GetString("ResponseGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nochg.
        /// </summary>
        internal static string ResponseNoChangeGood {
            get {
                return ResourceManager.GetString("ResponseNoChangeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nohost.
        /// </summary>
        internal static string ResponseNoHost {
            get {
                return ResourceManager.GetString("ResponseNoHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !yours.
        /// </summary>
        internal static string ResponseNotYours {
            get {
                return ResourceManager.GetString("ResponseNotYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Host&gt;.
        /// </summary>
        internal static string TagHost {
            get {
                return ResourceManager.GetString("TagHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IP&gt;.
        /// </summary>
        internal static string TagIP {
            get {
                return ResourceManager.GetString("TagIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IPv4&gt;.
        /// </summary>
        internal static string TagIPv4 {
            get {
                return ResourceManager.GetString("TagIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;IPv6&gt;.
        /// </summary>
        internal static string TagIPv6 {
            get {
                return ResourceManager.GetString("TagIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Password&gt;.
        /// </summary>
        internal static string TagPassword {
            get {
                return ResourceManager.GetString("TagPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Token&gt;.
        /// </summary>
        internal static string TagToken {
            get {
                return ResourceManager.GetString("TagToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Username&gt;.
        /// </summary>
        internal static string TagUsername {
            get {
                return ResourceManager.GetString("TagUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
